### ISSUE TITLE
V4: Options can now have `number` or `boolean` values

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-lib-dotnet#413]
In app-frontend v4, after the JsonPatch change, option lists can now be configured to hold `number` or `boolean` (or `null`, I guess) values. It is possible to configure right now in app-frontend, in the various ways options can be provided:

- Via static `options` on a component in the layout config file
- In API-options (static json file on disk, custom dynamic options)
- Derived from repeating group structures (aka `source`)

However, this currently crashes on the backend, as the layout engine there still requires strings.

### Acceptance criterias
- [x] Static Json option files can use string, number, bool og null as types in value property
- [ ] Dynamic option implementations can specify the types mentioned as well
- [ ] You can combine null with other types

**Comment by ivarne** [comment]
You seem to be referring to a case when an options component has a binding to a field that is of a non-string type. I'm not sure if this something that worked in v3 and is broken in v4, or a "nice to have feature" that you think is easy to add?

Currently backend uses the `AppOptions` class with a `.Value` property of type `string` for all handling of options (json, IAppOptionsProvider, Layout parsing):

https://github.com/Altinn/app-lib-dotnet/blob/e932fb0578177540094ec8e21b9800d92454a915/src/Altinn.App.Core/Models/AppOption.cs#L6-L11

* Changing this to `object?` would require a lot of care for all the different contexts this class is used. We can't say `string|number|bool` in C# 😭 

* A workaround might be that backend converts `"true"` to `true` (and so on) for API responses when it should be a simpler type, but we can't really do that, because an option might be used in multiple options components with binding to different types, and the same API can't return multiple types. Frontend kan look at the component and do the parse the strings from the API to match the data type of the binding field. That would ensure that the PATCH endpoint works as well, because the data type will match the model class.
* Another fix might be to look at the code that applies JsonPatch operations and see if we somehow can accept a patch that sets a boolean value to `"true"` or an integer to `"11"` without complaining.

Any preferences?

**Comment by olemartinorg** [comment]
As per your bullet points:
1. That's what I imagined, yes. If these can be either string, number or boolean now, the different cases must be handled in the backend as well, I would think.
2. "Frontend kan look at the component and do the parse the strings from the API to match the data type of the binding field. That would ensure that the PATCH endpoint works as well, because the data type will match the model class." - yup, that's what we do in v4 now. No real need for the backend to convert values for us on the response, but we now _support_ boolean/number values in the response.
3. No need for that, frontend already sends the correct type to the backend. We've had long-term goals to support this, and now that we do, I don't think there's any point in going one step backwards.

I'm not sure if the bullet points were meant to be alternative solutions to the same problem, so to rephrase the original problem I want solved here:

As an app developer, when we now support storing number/boolean values in the data model for options-components, I would like to be able to _define_ the options in an app using number/boolean values as well. Setting options to have a `true` and `false` value no longer fails in app-frontend, but it fails when backend is handling the save, i.e. when it parses the layout to load options. So yes, I would imagine `AppOption` should support a non-string `Value` property now.

**Comment by ivarne** [comment]
Thanks for rephrasing

We seem to talk somewhat past each other, so maybe writing summaries we might develop a shared understanding:
Everything works right now, but you opened this issue because it is somewhat awkward for frontend to get `"value": "42"` instead of `"value": 42`, for an option list that is mapped to a number, but you already have the code to support it in v4 now and return a proper number to the PATCH endpoint?

There isn't a great way in C# to say that a property can be bool|double|string, but not any other type, that make it intuitive for app devs with limited C# experience to create options providers.

**Comment by olemartinorg** [comment]
> There isn't a great way in C# to say that a property can be bool|double|string, but not any other type, that make it intuitive for app devs with limited C# experience to create options providers.

Allright, so let's skip that one. There's still other ways to define options, via:
- Static lists (in json files)
- Static lists (in the layout file/component configuration)
- Via repeating groups

Is is possible for these to support `bool|double|string` on the backend? It is support in JsonSchema, so even novice developers should understand that an object is not valid there. Right now, specifying a `boolean` in a static list of options will crash the backend, but not the frontend.

**Comment by ivarne** [comment]
Yes! Sorry for being dense, thanks for sticking with me.

I can fix it so that you can use Boolean or number in any place where an option value is defined in json (with the minor issue that apis will return them as strings)

**Comment by olemartinorg** [comment]
> with the minor issue that apis will return them as strings

Ah, yes, that's fine! :raised_hands:

**Comment by ivarne** [comment]
I think I have a solution that would solve all issues in a backwards compatible way. `.Value` is still a string, but I add a separate property storing the json type while deserializing and ensure that I serialize to the same json type. Options providers can set the type enumeration manually if they don't want string.

If we want to enforce type correctness you can remove your conversion code and just error.

**Comment by olemartinorg** [comment]
Added a new issue to fix the remaining issues in app-frontend:
- https://github.com/Altinn/app-frontend-react/issues/1790

**Comment by ivarne** [comment]
Fixed by #417
