### ISSUE TITLE
Form data save should return HTTP 200/201

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-lib-dotnet#52]
## Describe the bug
When an app contains calculation in the `CalculationHandler.cs`, a PUT call to update the formdate of the instance returns a `303 See other` as response code without a Location in the response headers. And k6 tests fail expecting a location response header on a 303 response. 

Refer this [link](https://datatracker.ietf.org/doc/html/rfc7231#section-6.4.4) where it says location is must on 303 responses.

## To Reproduce
1. Start an app instance that has logic defined in the `calculationhandler.cs`
2. Send a PUT call to update the form data of the instance
3. The response code is 303 and the response header misses the parameter location.

## Expected behavior
303 responses should be have location in the response headers

## Additional info
env: at21
app: ttd/security-level1-app

## Acceptance criteria
- [ ] Should work with V3 of frontend.

**Comment by SandGrainOne** [comment]
Adding a location header is causing new errors. The new Location header is making the app frontend follow the URI automatically instead of using the body of the 303 response. This in itself is bad and something we must avoid. The point of the 303 response was to include changes in a dictionary instead of having the client request the full data blob.

~The request being made because of the Location Header also fails: ERR_CONNECTION_REFUSED.~

The request were failing because the Location value where pointing to a https address (LocalTest testing). Changing that to http resolved that issue, but it did not fix anything else. 

Found this: https://stackoverflow.com/a/343359/5097336
Paraphrased: "It is not possible to prevent the browser from following redirects when sending XMLHttpRequest-s"

What we have today works. It just doesn't comply with the standard for a 303 response. If complying with standards is important enough we must reconsider using 303 and find a different solution.

The work put into this issue so far is in branch: https://github.com/Altinn/altinn-studio/tree/feature/6248-Status-SeeOther-RequiresLocationHeader

**Comment by olemartinorg** [comment]
IMO the status code should be 200, and we should just be checking if the response contains the change dictionary. HTTP status codes were not meant to be used for this, and 3xx status codes are absolutely meant for redirects.

**Comment by olemartinorg** [comment]
Adding this to `fe-v4` and milestone 8. Frontend v3 has supported returning 200 for a long time now, and still having to fall back to handling changes on HTTP 303 in the new formData rewrite in frontend v4 is just sad. Hoping we can fix this.

**Comment by olemartinorg** [comment]
As we no longer use the PUT endpoint in app-frontend, this is no longer a pain-point we have. All the endpoints we now use responds with standards-compliant status codes (2XX), so I'll remove the `fe-v4` label.

**Comment by olemartinorg** [comment]
Tested from latest v3 branch in frontend. Nothing seem to be affected by this change.
