### ISSUE TITLE
Elements with attributes is not deleted

### ISSUE THREAD

**Issue by kentare** [Altinn/app-lib-dotnet#552]
### Description of the bug

When using attributes in the XSD is it not possible to delete the element after a user inserts a value in an input field. Behaviour is present when the element is set as nillable. 

## 1. No value (initial, valid)
![image](https://github.com/Altinn/app-lib-dotnet/assets/24462806/b78c1135-e4a2-4f8c-aeba-d694d5b1cd60)
```xml
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
```

## 2. User written value (valid)
![image](https://github.com/Altinn/app-lib-dotnet/assets/24462806/11ec8c4c-eaf4-4177-bbfd-773af75a1c44)
```xml
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <aarets orid="30320">123</aarets>
</model>
```

## **BUG:** 3. Trying to delete value (invalid, should be the same as no value)
![desimal1](https://github.com/Altinn/app-lib-dotnet/assets/24462806/ff3de4b6-f0d2-4035-851c-44ae7fe24bc4)
```xml
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <aarets orid="30320">0</aarets>
</model>
```
Expected and desired behaviour:
The value for this needs to be the same as `1. No value`. `0` is a valid user inputted value, but not a valid value for deletion. 

## Repro from repo
1. Clone minimal reproduction repo: https://altinn.studio/repos/kentare/xmltext-decimal-repro 
2. Start the app
3. Insert a value 
4. Inspect XML
5. Delete value 
6. Inspect XML

### Additional Information

The model is uploaded to altinn.studio to generate the schema and classes. 

The XSD can be found here: https://altinn.studio/repos/kentare/xmltext-decimal-repro/src/branch/master/App/models/model.xsd 

The issue has been discussed here: https://altinn.slack.com/archives/C02EJ9HKQA3/p1710493123111109 

Might be related to: #517 

Discovered in this repo: https://altinn.studio/repos/brg/aarsregnskap-ideelle-202402 

This affects a _minimum_ of 10 apps that is in the process to migrate from Altinn 2 to Altinn 3. These can not be released in production with this bug present

**Comment by ivarne** [comment]
@mirkoSekulic (@olemartinorg)The sample app works fine with a class that actually uses a nullable decimal type for `value`.

Should we update Altinn Studio to generate something like this?

```diff
diff --git a/App/models/model.cs b/App/models/model.cs
index 697996d..a9b9296 100644
--- a/App/models/model.cs
+++ b/App/models/model.cs
@@ -22,9 +22,20 @@ namespace Altinn.App.Models.YttersteObjekt
   {
     [RegularExpression(@"^-?[0-9]{0,15}$")]
     [Range(Double.MinValue,Double.MaxValue)]
-    [XmlText()]
+    [XmlIgnore]
     [Required]
-    public decimal value { get; set; }
+    public decimal? value { get; set; }
+
+    [XmlText]
+    [System.Text.Json.Serialization.JsonIgnore]
+    public string valueAsString
+    {
+      get => value?.ToString();
+      set
+      {
+        this.value = value == null ? null : (decimal?)decimal.Parse(value);
+      }
+    }
 
     [XmlAttribute("orid")]
     [BindNever]
```

`decimal.Parse` seems to be culture aware, but I'm not sure if that would cause problems with sometimes serialising fractions with `,` and sometimes with `.`.

**Comment by olemartinorg** [comment]
Oh, this is the issue that's in many ways duplicate to:
- #517

I think it's worth investigating more here, including figuring out what happens and why this seemingly works with the PUT endpoint in frontend v3.

There's also some other considerations (beyond making the app work and not crash):
- How to handle existing apps, including those that aren't using Studio to regenerate models any longer (upgrade script?)
  - If we go this route of fixing this in the model generation, how do we alert app developers that they haven't run the upgrade yet?
- What's the content of the generated XML and/or JSON? I'm under the impression that the expected behaviour (from the app developers side, at least) is that we remove `aarets` as soon as you delete the content in `aarets.value`.

**Comment by ivarne** [comment]
I think I have a pretty good understanding now. #517 is very similar, but a different issue with how `[XmlText]` works in C# xml.

First: Studio generates C# classes with `[XmlText]` annotations in order to have attributes on a value. This is required in order to generate xml that validates with the old xsd files that was typically used in Altinn 2 `<tag orid="122">value<tag/>`. Without the attribute we use `[XmlElement]` which we have solved these issues for.

#552 (This issue): `[XmlText]` in C# serialisation library does not support nullable value types, thus Altinn Studio generates models with plain value types that gets set to `0` when the parent object is initialised. This can be solved if Altinn Studio uses the trickery I suggested earlier. We could potentially assume that the attributes are always `fixed`, and can be ignored so that the whole tag can be removed to support nullable that way, but it seems somewhat brittle.

#517: `[XmlText]` It looks like C# serialisation does not want to preserve values with only spaces in `[XmlText]` properties. This means that when you try to store `" "` to backend, you get `" "` back immediately, but `null` back later. The obvious solution is for frontend to stop sending json patch `"TEST"` operations when just updating a single leaf value. Crashing here is a frontend problem, because it sends a `test` operation and does not handle its failure.

Last: Both issues existed in v7/v3 also, but the bug was not caught, because backend only reported the changes it made, not the full current state in storage. If you write spaces to an `[XmlText]` string or revert to empty string after having had a number in an `[XmlText]` decimal, you will see these two bugs in v3 after reloading the page.

**Comment by kentare** [comment]
> I'm under the impression that the expected behaviour (from the app developers side, at least) is that we remove `aarets` as soon as you delete the content in `aarets.value`.

That is correct.

> #552 (This issue): `[XmlText]` in C# serialisation library does not support nullable value types, thus Altinn Studio generates models with plain value types that gets set to `0` when the parent object is initialised.

Can add to this that we same problem for nullable boolean values that initializes to false.

**Comment by ivarne** [comment]
I think the proper resolution of this issue would be the fixes proposed in https://github.com/Altinn/altinn-studio/issues/12674

**Comment by martinothamar** [comment]
@ivarne is this fixed already?

**Comment by ivarne** [comment]
Yes, I believe that https://github.com/Altinn/altinn-studio/pull/12734 in combination with the latest version of app lib will fix this issue when new c# code is generated in studio for the app

**Comment by martinothamar** [comment]
Just tested this with the repro app after updating to the latest v8 libs and regenerating model in Studio

After inputting `123`:

![Image](https://github.com/Altinn/app-lib-dotnet/assets/5425986/dceadb54-9336-4be1-a80d-f1657d28cc06)

After backspacing and removing the input - it becomes empty, and XML:

![Image](https://github.com/Altinn/app-lib-dotnet/assets/5425986/5af66e71-7983-486c-9292-0dc7bb0af5fb)

Diff after regen:

![Image](https://github.com/Altinn/app-lib-dotnet/assets/5425986/df0bd71a-dc10-4932-9add-d93c49ba7af0)

**Comment by kentare** [comment]
Verifisert at dette løser problemet vårt. Takk!
