### ISSUE TITLE
FileUpload in removed pages should not give validation errors for missing files

### ISSUE THREAD

**Issue by jostein-skaar** [Altinn/app-lib-dotnet#81]
## Describe the bug
When using sporvalg to remove pages from LayoutSettings.Pages.Order list in `GetPageOrder()` in App.cs, missing file uploads may prevent sending in instance.

## To Reproduce
1. App with 3 pages (Page1, Page2 and Page3)
2. On Page1: A checkbox with label "Hide Page2" (and code in GetPageOrder() to remove Page3)
3. On Page2: A FileUpload (with "minCount": 1 in applicationmetadata.json)
4. On Page3: Send in button
5. When Page2 is removed, sending in gives validation error because of missing file.

## Expected behavior
When a FileUpload is present in one or more pages, it should not fail validation if all of those pages are removed because of "sporvalg".

**Comment by lvbachmann** [comment]
Minimum solution: If we have a workaround this should be documented.

**Comment by nkylstad** [comment]
This is as expected, because validation of attachments is done separately from validation of form data. Thus if an attachment type has set `minCount: 1` in applicationMetadata.json, it will never be allowed to submit/move to the next step, because at least 1 data element (in this case the data element for the attachment) has validation result as not ok. 

This validation is done completely separately from frontend (with pages shown/hidden), and is the same validation both for submitting via frontend and for submitting via end user systems/APIs. Therefore bringing page order and visible/not visible on component level into this validation is probably not something we want to do.

Workaround is to set the dataelement that the FileUpload is connected to to be optional (minCount: 0) in applicationMetadata.json and use custom validation in ValidationHandler to validate the attachments in the relevant cases where it is expected that it is included.

**Comment by jostein-skaar** [comment]
We are using this workaround. We kept `"minNumberOfAttachments": 1,` in the formLayout to keep getting at least client side validation when the FileUpload is visible. Side effect: Touching the Vedlegg component in the ui-editor in Altinn Studio sets minCount back to 1 in applicationmetadata.json. So we make sure no one touches this for now.

**Comment by jostein-skaar** [comment]
Wouldn't writing custom validation for the app mean that submitting via frontend and submitting via end user systems/APIs would have different rules for the actual attachement. Submitting via the latter could actually omit the attachment? In some cases the attachment is required by us. No matter how it is submitted.

**Comment by nkylstad** [comment]
> Wouldn't writing custom validation for the app mean that submitting via frontend and submitting via end user systems/APIs would have different rules for the actual attachement. Submitting via the latter could actually omit the attachment? In some cases the attachment is required by us. No matter how it is submitted.

Custom validation written in ValidationHandler is run when submitting both from frontend and APIs. The custom validation would have to take into account that there are certain cases where the attachment is required, f.ex. depending on what the user has answered in the form, and then in those cases check that the attachment is present. This validation would then be run both for submissions from frontend and APIs.

**Comment by jostein-skaar** [comment]
It is good the validation runs for both!

This is what I thought regarding to this:
1. An app may have multiple pages. 
2. FileUpload may be present on any number of the pages. 
3. An app may have "sporvalg". 
4. Some "sporvalg" may hide a page with FileUpload. 
5. It should be able to send in.

Is number 2 and 4 not intended use cases? Are we using FileUpload wrong?

**Comment by ivarne** [comment]
Now that #23 is coming with a way to read layout files in C# issues like these become much easier to do.

**Comment by ivarne** [comment]
We will keep this behaviour of always respecting applicationmetadata `"minCount"`, but in #771 I suggest that we should read and respect layout components configured with `minNumberOfAttachments` to automatically get server errors, instead of requiring apps to write a custom validator.
